### ISSUE TITLE
性能检查类似工具

### ISSUE THREAD

**Issue by sdlbp** [joggerplus/JPFPSStatus#8]
非常喜欢你的这个开源库,我感觉这是对于开发非常有帮助的.  请教你关于性能检测方面,你所知的其它工具,最好是可以准确的定位出瓶颈点

**Comment by coderyi** [comment]
说实话，我很少用性能检测的库，目前好像也没有检查所有的，只能用instruments，不过单个方面的性能检测应该还是有很多库的，你具体想检查哪些方面呢？

**Comment by sdlbp** [comment]
目前来说,是没有特别偏重点. 不过对这一块感兴趣,因为看到你的 JPFPSStatus ,所以向你了解这方面的知识. 可能 , 我想要的 还是类似 instruments 的工具吧, 对 instruments 加深下了解应该可以学到更多的这方面的知识.

**Comment by coderyi** [comment]
GitHub还是有很多工具的，只不过要慢慢找
